# /admin/config.yml

# This backend configuration is specifically for Netlify's Git Gateway.
# It allows you to invite users to the CMS without giving them access to your GitHub repo.
backend:
  name: git-gateway
  branch: main # Or master, depending on your default branch name

# Where to store uploaded media files in your repo
media_folder: "public/assets"
public_folder: "/assets"

# These are the content types you can edit in the CMS.
collections:
  # A "folder" collection for your projects. You can add/edit/delete projects.
  - name: "projects"
    label: "Projects & Deployments"
    folder: "src/data/projects"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Status", name: "status", widget: "select", options: ["Completed", "Ongoing", "Archived"] }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Metric Summary", name: "metric_summary", widget: "string" }

  # A "file" collection for managing page sections in single files.
  - name: "page_content"
    label: "Page Content"
    files:
      - label: "Site Settings & SEO"
        name: "settings"
        file: "src/data/settings.json"
        fields:
          - { label: "Your Name", name: "name", widget: "string" }
          - { label: "Hero Tagline", name: "tagline", widget: "string" }
          - { label: "Meta Description", name: "meta_description", widget: "text" }
          - label: "JSON-LD Schema"
            name: "json_ld"
            widget: "object"
            fields:
              - { label: "Website URL", name: "url", widget: "string" }
              - label: "Social Profile URLs"
                name: "sameAs"
                widget: "list"
                field: { label: "Profile URL", name: "url", widget: "string" }
      
      - label: "Certifications"
        name: "certifications"
        file: "src/data/certifications.json"
        fields:
          - label: "Certification Items"
            name: "certs"
            widget: "list"
            fields:
              - { label: "Logo", name: "logo", widget: "image" }
              - { label: "Alt Text", name: "alt", widget: "string" }
              - { label: "Link URL", name: "url", widget: "string" }

      - label: "Tools & Tech Stack"
        name: "tools"
        file: "src/data/tools.json"
        fields:
          - label: "Tool List"
            name: "tools"
            widget: "list"
            field: { label: "Tool Name", name: "name", widget: "string" }

      - label: "Contact & Availability"
        name: "contact"
        file: "src/data/contact.json"
        fields:
          - { label: "Primary CTA URL (Book a Call)", name: "primary_cta_url", widget: "string" }
          - label: "Other Links"
            name: "links"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
